default_context:
  project_name: 'fastapi-fullstack'
  project_slug: 'fastapi-fullstack'
  domain_main: 'fastapi-fullstack.com'
  domain_staging: 'stag.fastapi-fullstack.com'
  docker_swarm_stack_name_main: 'fastapi-fullstack-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-fullstack-com'
  secret_key: 'ham8germ'
  first_superuser: 'admin@fastapi-fullstack.com'
  first_superuser_password: 'ham8germ'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-fullstack.com", "https://stag.fastapi-fullstack.com", "https://fastapi-fullstack.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-fullstack.com'
  postgres_password: 'ham8germ'
  pgadmin_default_user: 'admin@fastapi-fullstack.com'
  pgadmin_default_user_password: 'ham8germ'
  traefik_constraint_tag: 'fastapi-fullstack.com'
  traefik_constraint_tag_staging: 'stag.fastapi-fullstack.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ham8germ'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
